name: gsheet_to_arb
version: 1.0.1
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ">=2.3.1"
  intl: ^0.19.0
  intl_generator:
    git:
      url: https://github.com/Elr03/intl_generator.git
  path: ">=1.8.1"
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  code_builder: ">=4.1.0"
  json_annotation: "^4.5.0"
  file_utils: ">=1.0.1"
  logging: "^1.0.2"
  recase: "^4.0.0"

  quiver: "^3.1.0"

  yaml: ">=3.1.1"

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  pedantic: ^1.11.1
  test: ^1.25.8
