name: gsheet_to_arb
version: 1.0.1
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  intl: ">=0.17.0 <0.18.0"
  intl_generator:
    #git: git://github.com/kiwi-bop/intl_generator
    git:
      url: https://github.com/kiwi-bop/intl_generator
      # ref: feature/migrationNullSafety
  path: ">=1.8.0 <2.0.0"
  googleapis_auth: ^1.1.0
  googleapis: ^7.0.0
  code_builder: ">=4.0.0 <5.0.0"
  json_annotation: "^4.0.1"
  file_utils: ">=1.0.0 <1.1.0"
  logging: "^1.0.1"
  recase: "^4.0.0"
  quiver: "^3.0.1"
  yaml: ">=3.1.0 <3.2.0"
  petitparser: ">=4.0.0 <5.0.0"

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  pedantic: ^1.11.0
